#!/bin/bash

go run 2.workqueue/producer.go msg.
go run 2.workqueue/producer.go msg..
go run 2.workqueue/producer.go msg...
go run 2.workqueue/producer.go msg....
go run 2.workqueue/producer.go msg.....