#!/bin/bash

go run 6.publish_subscribe/producer.go msg.
go run 6.publish_subscribe/producer.go msg..
go run 6.publish_subscribe/producer.go msg...
go run 6.publish_subscribe/producer.go msg....
go run 6.publish_subscribe/producer.go msg.....